name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
machine_id: 1
start_time: "2023-12-28"

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

auth:
  jwt_expire: 8760

mysql:
  host: "host.docker.internal"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "web"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "host.docker.internal"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
